Set CA for adding and deleting contacts, as well as changing the DAO
az19642/aimessage pull request #34
Opened 2023-12-03 07:19 UTC by Ahassini04

For the DAO I made it such that it now holdsand attribute of the logged in user entity which can be used in the different use cases.

2023-12-04 22:03 UTC, az19642 commented on src/main/java/interface_adapter/mutating_contacts/MutatingContactsController.java
Good. This class acts as the controller for the specific use case and depends on an Input Boundary and creates Input Data to execute the Input Boundary (interactor) with.

2023-12-04 22:05 UTC, az19642 commented on src/main/java/use_case/mutating_contacts/MutatingContactsInputBoundary.java
Good. Input Boundary contains only the execute method, adhering to ISP.

2023-12-04 22:06 UTC, az19642 commented on src/main/java/use_case/mutating_contacts/MutatingContactsInputData.java
Good. Input Data contains all the necessary data to be used in the interactor.

2023-12-04 22:09 UTC, az19642 commented on src/main/java/use_case/mutating_contacts/MutatingContactsInteractor.java
Good. Manipulates data using the Data Access Interface (implemented by MongoUserDataAccessObject) and calls the Presenter appropriately with the required output data (in this case, none for the success view and error messages for the fail view)

2023-12-04 22:10 UTC, az19642 commented on src/main/java/use_case/mutating_contacts/MutatingContactsUserDataAccessInterface.java
Good. Follows ISP. All the specific methods required by the use case is in this interface while the actual data access object implements this (of many).

2023-12-04 22:28 UTC, az19642 requested changes
Good implementation overall of the the adding/removing contacts use case. Interactor test is flawed.

**Coding style** 
Good. Private and public access modifiers are used where appropriate and the files created for the use case follow the clean architecture packaging.

**Correctness**
Correctness cannot be tested by running the application (non-testing) as the listeners for this use case have not been implemented yet.

**Tests**
The interactor test is invalid and produces an error. You must rethink how you will test this interactor since your MutatingContactsUserDataAccessInterface does not specify a method to set the current user so the current user is null during your test.

**Clean Architecture + SOLID**
Good. All files mimic clean architecture, inherently adhering to SOLID.

**Javadoc**
Good. All public classes and methods were properly documented and explains the point of the class/method.

**Clarity**
PR description can be more descriptive. Explain the reason for the DAO being changed this way. Could also elaborate on the actual use case itself, e.g.: why did you decide to do adding/removing contacts in one use case?

2023-12-04 23:47 UTC, jchrisoh commented on src/test/java/use_case/mutating_contacts/MutatingContactsInteractorTest.java
> +                new CommonUserFactory()
Resolved.

2023-12-05 00:04 UTC, az19642 commented
Looks good, interactor test is correct and passes.

2023-12-05 00:04 UTC, az19642 approved these changes

2023-12-05 00:05 UTC, merged